get http://localhost:3000/photos

###
get http://localhost:3000/photos/1

###
POST http://localhost:3000/photos
content-type: application/json

{
  "input_name": "summer",
  "input_width": 200,
  "input_height": 500
}


###
PATCH http://localhost:3000/photos/1
content-type: application/json

{
  "input_name": "fall",
  "input_width": 400,
  "input_height": 400
}

###
DELETE http://localhost:3000/photos/2